SELECT TOP 100 * FROM customer

-- 1. Total revenue generated by Male vs Female Customers

SELECT gender, SUM(purchase_amount) AS total_revenue FROM customer
GROUP BY gender

-- 2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (
	SELECT AVG(purchase_amount) FROM customer
)

-- 3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS average_rating FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC

-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amt FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non-subscribers

SELECT COUNT(customer_id) AS no_of_customers, subscription_status, ROUND(AVG(purchase_amount),2) as avg_spend, ROUND(SUM(purchase_amount),2) as total_revenue 
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,
CAST(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*)
    AS decimal(5,2)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
	SELECT customer_id, previous_purchases, 
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
	FROM customer
) SELECT customer_segment, COUNT(*) AS number_of_customers FROM customer_type 
GROUP BY customer_segment

-- 8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
	SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
) SELECT * FROM item_counts
WHERE item_rank <= 3

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

-- ALTERNATE CODE
--SELECT subscription_status, 
--COUNT(CASE
--	WHEN subscription_status = 'Yes' AND previous_purchases > 5 THEN 1
--	WHEN subscription_status = 'No' AND previous_purchases > 5 THEN 2
--END) AS repeat_buyers
--FROM customer
--GROUP BY subscription_status

-- GOOD CODE
SELECT subscription_status,
COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

-- 10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS revenue FROM customer
GROUP BY age_group
ORDER BY revenue DESC